    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: web-app
      labels:
        app: web-app
      namespace: default
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: web-app
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: web-app
        spec:
          containers:
            - image: nigercode/web-app
              imagePullPolicy: Always
              name: web-app
              ports:
                - containerPort: 80    

    apiVersion: v1
    kind: Service
    metadata:
      name: web-app:v1.0
      labels:
      app: web-app:v1.0
    spec:
      type: LoadBalancer
      selector:
      app: 
        ports:
        - port: 80
            targetPort: 8086
            protocol: TCP 